spring:
  application:
    name: store
stripe:
  apiURL: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://mytest.gmail.com
  port: 5761